cookie:
  expiry_days: 90
  key: larp_character_sheet
  name: la_character_sheet_login
credentials:
  usernames:
    adidner:
      email: adidner@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Aaron Didner
      password: $2b$12$lseT/v8UJt9M/heIi2HoXeVt.vxhwY0VrxZoWW3PioLgmwS51qpw.
    caenis_macneary:
      email: nhunter2001@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Niki Hunter
      password: $2b$12$csvHP2oeZiC9EraMmpez5eKDWgefAr48EbhG7aJv8nFDptx0NrQsi
    ghostfox:
      email: tigerpaw.hb.1997@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Kara
      password: $2b$12$KiF6yEr0rZK6Ro4/dS9V9uLZr2zmwwtv67XSgtCYfWpbOhLQVVI9C
    mbarron:
      email: maura.mcnamee.12@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Maura
      password: $2b$12$D5zVITdHoe5q2G3IQ/2eR.2fe5TdFEFdBicgRZ5aiaOlQE6WQw7cW
    ntdens:
      email: ntdens@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Nate Densmore
      password: $2b$12$ZHdynQyq8MUpUG0U5rxrm.k8sy6WMkpiy4lyKUOlh4g6IjasAnwuW
    orion:
      email: Fontisian@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Orion
      password: $2b$12$JfQlvMWf2G/KzACw93SHu.dp9bCcBbff.2979Y05wEM.hvy7VEZg6
    toland:
      email: toland@blacksky.wiki
      failed_login_attempts: 0
      logged_in: false
      name: Toland
      password: $2b$12$93DUOYX40VsNib9PbB6Y6O/sGpzD78FUshdXbuEUpEMAD/6hMYrJG
