cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    ntdens:
      email: ntdens@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Nate Densmore
      password: $2b$12$ZHdynQyq8MUpUG0U5rxrm.k8sy6WMkpiy4lyKUOlh4g6IjasAnwuW
